const attackDescriptions = {
    CHOMP: "A quick Dark-type bite that stuns the target for a short duration. Low damage but great for disruption.",
    DASH: "A defensive maneuver that teleports the player up or down to avoid incoming attacks while leaving a brief visual trail.",
    BLOAT: "A recovery move that restores 10 HP. The user is briefly vulnerable while healing.",
    PUDDLE: "Creates a shrinking Water-zone that slows anyone inside to 10% speed and deals 2 damage per tick.",
    STATIC: "An Electric discharge that stuns the user for 2s and the target for 1s. Deals 1 damage. High risk, high reward stun.",
    FIREBOLT: "Unleashes 1-5 random Fire projectiles that travel across the screen, dealing 8 damage each on impact.",
    "SHADOW STEP": "Teleports the user to the top or bottom of the screen, leaving a shadow trail that stuns the target and creates a dark trap at the new location.",
    BITE: "A lunging Basic attack that deals 5 damage and inflicts a significant 1.9s stun on hit. Stuns the user briefly on startup.",
    HARDEN: "A Plant-type buff that restores 5 HP and increases Defense by 5. The user is rooted in place for 5.5s during the process.",
    SNAP: "A very fast, low-cooldown strike dealing 2 damage. Knocks back the target, but can also knock back and damage the user if used poorly.",
    "WIND MILL": "Creates a shrinking Air vortex around the user for 5s that pulls the target inward, ending with a final push back.",
    "WIND SLASH": "Fires a tall, vertical blade of wind that travels across the stage, dealing 10 Air-type damage on contact.",
    BEAM: "A channeled Light attack that can be aimed in four directions. Deals 8 damage and continuously pushes the target back for 6s.",
    DECONSTRUCT: "A massive Metal-type buff. Over 6s, it repeatedly boosts Health, Speed, and Attack, but reduces Defense by 10 each pulse.",
    PECK: "A quick aerial lunge dealing 3 Air damage. Covers a small forward distance and stuns the target for 0.5s.",
    CLAMP: "The user lunges forward; if it connects, it grabs the target and suppresses them for 5s while dealing 13 Metal damage.",
    "FLASH BANG": "Fires a Light projectile. If moving, it triggers a massive close-range 4s stun; if stationary, the projectile grows as it travels.",
    FIREWORK: "A long-charge Fire attack. The user spins to aim the launch angle and then rockets at high velocity, dealing 15 damage on impact.",
    BEATDOWN: "A high-speed rush that carries the target into the air for a multi-hit combo. Damage scales based on the momentum of the initial hit.",
    SNORT: "A Basic buff that increases Attack by 5. Note: This enrages the target, nearly doubling their Speed for 6 seconds.",
    CHARGE: "An Electric channel move. Holding 'Up' stacks Attack multipliers for 12s. The charge eventually fizzes out.",
    "FADE AWAY": "The user turns into a shadow for 2s, gaining 999 Defense and massive Speed while stunning any nearby enemies.",
    "BODY SLAM": "A leaping Basic attack. Damage scales with the user's Size and Defense; it hits hardest when slamming down from above.",
    SHED: "A Basic restoration move. After a long channel, heals 12 HP and boosts Attack/Speed while lowering Defense.",
    SNATCH: "A Dark-type strike that drops a shadow box from above. If it hits, the target is stunned for a long duration.",
    "VICIOUS BITE": "A powerful Beast-type snap that deals 10 damage. On hit, it stuns the target and pulls them toward the user for follow-up attacks.",
}