const attackDescriptions = {
    CHOMP: "A quick Dark-type bite that stuns the target for a short duration. Low damage but great for disruption.",
    DASH: "A defensive maneuver that teleports the player up or down to avoid incoming attacks while leaving a brief visual trail.",
    BLOAT: "A recovery move that restores 10 HP. The user is briefly vulnerable while healing.",
    PUDDLE: "Creates a shrinking Water-zone that slows anyone inside to 10% speed and deals 2 damage per tick.",
    STATIC: "An Electric discharge that stuns the user for 2s and the target for 1s. Deals minimal damage but enables follow-ups.",
    FIREBOLT: "Unleashes 1–5 Fire projectiles that travel across the screen. Each fireball deals damage on contact.",
    "SHADOW STEP": "Teleports the user to the top or bottom of the arena, leaving behind a shadow that stuns enemies and creates a lingering dark threat.",
    BITE: "A lunging Basic attack that deals solid damage and heavily stuns the target. The user is briefly stunned on startup.",
    HARDEN: "A Plant-type buff that restores health and increases Defense. The user is rooted in place during the channel.",
    SNAP: "A lightning-fast strike with very low cooldown. Deals light damage and knockback, but can recoil if misused.",
    "WIND MILL": "Creates a shrinking Air vortex around the user that pulls enemies inward before pushing them away at the end.",
    "WIND SLASH": "Launches a vertical blade of compressed wind that travels forward, dealing Air damage on contact.",
    BEAM: "A channeled Light attack that can be aimed in four directions, continuously pushing enemies back while dealing damage.",
    DECONSTRUCT: "A powerful Metal-type self-buff that repeatedly boosts core stats over time at the cost of Defense.",
    PECK: "A quick aerial lunge that deals light Air damage and briefly stuns the target.",
    CLAMP: "A Metal-type grab attack. If it connects, the target is suppressed for several seconds while taking heavy damage.",
    "FLASH BANG": "Fires a Light projectile that behaves differently based on movement—either detonating nearby or growing larger as it travels.",
    FIREWORK: "A high-risk Fire attack that charges before launching the user at extreme speed, dealing massive damage on impact.",
    BEATDOWN: "A relentless rush that carries the target into a multi-hit combo. Damage increases based on momentum.",
    SNORT: "A risky Basic buff that increases the user's Attack while enraging the target, greatly boosting their Speed.",
    CHARGE: "An Electric channel move that stacks Attack multipliers while held. The charge fades if not released in time.",
    "FADE AWAY": "The user becomes a living shadow, gaining extreme Defense and Speed while stunning nearby enemies.",
    "BODY SLAM": "A heavy aerial slam whose damage scales with the user's size and Defense, hitting hardest from above.",
    SHED: "A long-channel recovery move that heals HP and boosts offensive stats at the cost of Defense.",
    SNATCH: "Drops a Dark shadow strike from above. If it connects, the target is heavily stunned and trapped in place.",
    "VICIOUS BITE": "A brutal Beast-type attack that snaps forward, stunning the target and pulling them closer for follow-up attacks.",
    TOTALITY: "A powerful Beast transformation that massively boosts stats, increases size, and restores health for a short duration before wearing off.",
    "TENTACLE SLASH": "Summons a descending Dark appendage that strikes from above, dealing damage and heavily stunning the target.",
    "CHRONIC SLAM": "A frenzied forward assault that repeatedly slams the enemy while scaling damage over time and chipping away at their health.",
    ERUPT: "Causes fiery debris to burst from above and scatter outward. Each flare travels independently and disappears on impact."
}
